version: '3.8'
   
services:
    django:
        build: ./COVID_Django
        container_name: KeepItDjango
        command: gunicorn KeepIt.wsgi:application --bind 0.0.0.0:5000
        volumes:
            - ./COVID_Django/:/usr/src/app/
            - static_volume:/usr/src/app/web/staticfiles
        expose:
            - 5000
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: KeepItDB
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
            - static_volume:/usr/src/app/web/staticfiles
    nginx:  
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - django
        
volumes:
    pgdata: